#!/bin/bash
#
#
#
# if [ -d "/.snapshots" ]
# then
#
# sudo umount /.snapshots
# sudo rm /.snapshots -rf
# sudo snapper -c root create-config /
# sudo btrfs subvolume delete /.snapshots
# sudo mkdir /.snapshots
# sudo mount -t btrfs -o subvol=@.snapshots /dev/... /.snapshots
#
# else
#
# sudo snapper -c root create-config /
#
# fi
#
#
# sudo snapper -c home create-config /home
#
# echo "ADD grub-btrfs-overlayfs TO END OF HOOKS ARRAY IN /etc/mkinitcpio.conf"
#
# read "press enter to continue..."
#
# sudo vim /etc/mkinitcpio.conf
#
# sudo mkinitcpio -P
#
# sudo systemctl enable snapper-cleanup.timer
#
# sudo systemctl start snapper-cleanup.timer
