#!/bin/bash

sudo snapper -c root create-config /

sudo snapper -c home create-config /home

echo "ADD grub-btrfs-overlayfs TO END OF HOOKS ARRAY IN /etc/mkinitcpio.conf (waiting 20s so you can read this)"

sleep 20

sudo vim /etc/mkinitcpio.conf

sudo mkinitcpio -P

sudo systemctl enable snapper-cleanup.timer

sudo systemctl start snapper-cleanup.timer
