#!/bin/bash
#
#
#
# if [ -d "/.snapshots" ]
# then
#
# sudo umount /.snapshots
# sudo rm /.snapshots -rf
# sudo snapper -c root create-config /
# sudo btrfs subvolume delete /.snapshots
# sudo mkdir /.snapshots
# sudo mount -t btrfs -o subvol=@.snapshots /dev/... /.snapshots
#
# ALSO NEED TO EDIT FSTAB?
#
# else
#
# sudo snapper -c root create-config /
#
# fi
#
#
# sudo snapper -c home create-config /home
#
# echo "ADD grub-btrfs-overlayfs TO END OF HOOKS ARRAY IN /etc/mkinitcpio.conf"
#
# read "press enter to continue..."
#
# sudo vim /etc/mkinitcpio.conf
#
# sudo mkinitcpio -P
#
# sudo systemctl enable snapper-cleanup.timer
#
# sudo systemctl start snapper-cleanup.timer
#
# sudo systemctl enable grub-btrfsd
# sudo systemctl start grub-btrfsd
#
# sudo /etc/grub.d/41_snapshots-btrfs
# sudo grub-mkconfig -o /boot/grub/grub.cfg
