#!/bin/bash

sudo pacman -S --needed git base-devel stow

chmod a+x ./install_yay

yay --version || ./install_yay

chmod a+x ./run_init

chmod a+x ./install

./install .

rm ~/.bashrc

ls -d */ | sed "s/\///" | xargs -I{} ./install {}

rustup default stable

ls -d */ | grep '^[^_]' | sed "s/\///" | xargs -I{} stow {} --ignore='^(init|pkg.txt)'

ls -d */ | sed "s/\///" | xargs -I{} ./run_init {}

