#!/bin/bash

sudo pacman -S i3

sudo pacman -S xorg

sudo pacman -S arandr

arandr

sudo pacman -S nerd-fonts

sudo pacman -S network-manager-applet

sudo pacman -S pulseaudio

sudo pacman -S dmenu

yay -S betterlockscreen
